### ISSUE TITLE
Can't run `python manage.py migrate` on a fresh install

### ISSUE THREAD

**Issue by cuducos** [rg3915/django-experience-2016#29]
I get the `django.db.migrations.exceptions.InvalidBasesError: Cannot resolve bases for [<ModelState: 'crm.Employee'>, <ModelState: 'crm.Seller'>]` error:

``` console
$ python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/cuducos/Sites/django-experience/.venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/Users/cuducos/Sites/django-experience/.venv/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/cuducos/Sites/django-experience/.venv/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/cuducos/Sites/django-experience/.venv/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/cuducos/Sites/django-experience/.venv/lib/python3.5/site-packages/django/core/management/commands/migrate.py", line 200, in handle
    executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
  File "/Users/cuducos/Sites/django-experience/.venv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 92, in migrate
    self._migrate_all_forwards(plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/cuducos/Sites/django-experience/.venv/lib/python3.5/site-packages/django/db/migrations/executor.py", line 118, in _migrate_all_forwards
    state.apps  # Render all -- performance critical
  File "/Users/cuducos/Sites/django-experience/.venv/lib/python3.5/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/cuducos/Sites/django-experience/.venv/lib/python3.5/site-packages/django/db/migrations/state.py", line 162, in apps
    return StateApps(self.real_apps, self.models)
  File "/Users/cuducos/Sites/django-experience/.venv/lib/python3.5/site-packages/django/db/migrations/state.py", line 228, in __init__
    self.render_multiple(list(models.values()) + self.real_models)
  File "/Users/cuducos/Sites/django-experience/.venv/lib/python3.5/site-packages/django/db/migrations/state.py", line 304, in render_multiple
    "for more" % (new_unrendered_models, get_docs_version())
django.db.migrations.exceptions.InvalidBasesError: Cannot resolve bases for [<ModelState: 'crm.Employee'>, <ModelState: 'crm.Seller'>]
This can happen if you are inheriting models from an app with migrations (e.g. contrib.auth)
 in an app with no migrations; see https://docs.djangoproject.com/en/1.9/topics/migrations/#dependencies for more
```

**Comment by cuducos** [comment]
`make delete_migrations` and `make migrate` (instead of `python manage.py migrate`) solved!
